#swagger-ui界面  http://localhost:8080/swagger-ui/index.html

# 配置端口号
server:
  port: 8080

spring:
  application:
    name: dic_platform

  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${dic.mysqldb.host}:3306/dic?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: ${dic.mysqldb.password}

  # 配置环境（dev 开发环境、prod 生产环境）
  profiles:
    active: prod

  devtools:
    restart:
      enabled: true
      exclude: application.yml,static/**,public/**

  resources:
    cache:
      cachecontrol:
        public: true
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 25920
      chain:
        strategy:
          fixed:
            enabled: true
            version: 1.0.0
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


#设置mybatis-plus的日志功能，可以看到mybatis-plus自动生成的sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
