dic:
  mysqldb:
    host: mysql
    password: 123456
  influxdb:
    host: influxdb2
    port: 8086
    token: UOfm9V_mz_u2qgSt0e-_BWEmcjBd9qno1TjOkwLiCNbxJExPgF7UBCqG9kIhzk0H99RjMJFvwjzNreK9F5IbUQ==
  mqtt:
    host: 1.14.135.194
    port: 1883